### ISSUE TITLE
Add exception based on number of visits

### ISSUE THREAD

**Issue by gittaca** [TheNamlessGuy/browser-history-cleaner#1]
Thank you for this add-on! It's so useful to protect software documentation pages from getting purged from browser history, just because I might not have visited them for a while :-)

As an additional exception, could you please consider adding something like "number of visits >= N"? That would help keep pages outside of the known set of domains.

Kinda like the opposite concept of https://addons.mozilla.org/en-GB/firefox/addon/one-and-only/

**Comment by TheNamlessGuy** [comment]
Hi! The latest version (0.2.0) should have the 'Page has been visited more than X times' option available. Note that:
1) This is per URL, not per domain.
2) Is something tracked by firefox itself.

In my testing, I found some that had a visitation count of 0, which doesn't make a whole lot of sense if you think about it. So I'm not sure how exact their tracking is.
